train_environments:
  - name: task1
    width: 64
    height: 32

    agent_mode: random
    env_mode: random

    nb_agents: 1
    nb_static_obstacles: 0
    nb_moving_obstacles: 0
    nb_targets: 1

    max_attempts: 100
    max_steps: 100

  - name: task2
    width: 64
    height: 32

    agent_mode: fixed_1
    env_mode: fixed_1

    nb_agents: 1
    nb_static_obstacles: 3
    nb_moving_obstacles: 0
    nb_targets: 1

    max_attempts: 100
    max_steps: 100

  - name: task3
    width: 64
    height: 32

    agent_mode: fixed_2
    env_mode: fixed_2

    nb_agents: 1
    nb_static_obstacles: 6
    nb_moving_obstacles: 0
    nb_targets: 1

    max_attempts: 100
    max_steps: 100

  - name: task4
    width: 32
    height: 32

    agent_mode: crossing
    env_mode: crossing

    nb_agents: 1
    nb_static_obstacles: 0
    nb_moving_obstacles: 1

    max_attempts: 100
    max_steps: 100

  - name: task5
    width: 64
    height: 32

    agent_mode: fixed_3
    env_mode: random

    nb_agents: 1
    nb_static_obstacles: 0
    nb_moving_obstacles: 3
    nb_targets: 1

    max_attempts: 100
    max_steps: 100

  - name: task6
    width: 64
    height: 32

    agent_mode: fixed_3
    env_mode: fixed_random_3

    nb_agents: 1
    nb_static_obstacles: 9
    nb_moving_obstacles: 2
    nb_targets: 1

    max_attempts: 100
    max_steps: 100

  - name: task7
    width: 64
    height: 32

    agent_mode: random
    env_mode: warehouse

    nb_agents: 1
    nb_moving_obstacles: 2
    nb_targets: 2

    margin: 2
    max_attempts: 100
    max_steps: 200

  - name: task8
    width: 32
    height: 32

    agent_mode: crossing
    env_mode: crossing

    nb_agents: 2
    nb_static_obstacles: 0
    nb_moving_obstacles: 0

    max_attempts: 100
    max_steps: 100

  - name: task9
    width: 64
    height: 32

    agent_mode: random
    env_mode: random

    nb_agents: 5
    nb_static_obstacles: 0
    nb_moving_obstacles: 1
    nb_targets: 3

    max_attempts: 100
    max_steps: 300

  - name: task10
    width: 64
    height: 32

    agent_mode: random
    env_mode: random

    nb_agents: 8
    nb_static_obstacles: 0
    nb_moving_obstacles: 1
    nb_targets: 3

    max_attempts: 100
    max_steps: 300

eval_environments:
  - name: eval1_random_1
    width: 128
    height: 64

    agent_mode: random
    env_mode: random

    nb_agents: 1
    nb_static_obstacles: 6
    nb_moving_obstacles: 0
    nb_targets: 2

    max_attempts: 100
    max_steps: 200

  - name: eval2_random_2
    width: 128
    height: 64

    agent_mode: random
    env_mode: random

    nb_agents: 1
    nb_static_obstacles: 0
    nb_moving_obstacles: 4
    nb_targets: 2

    max_attempts: 100
    max_steps: 200

  - name: eval3_random_3
    width: 128
    height: 64

    agent_mode: random
    env_mode: random

    nb_agents: 1
    nb_static_obstacles: 6
    nb_moving_obstacles: 4
    nb_targets: 2

    max_attempts: 100
    max_steps: 200

  - name: eval4_random_4
    width: 128
    height: 64

    agent_mode: random
    env_mode: random

    nb_agents: 2
    nb_static_obstacles: 6
    nb_moving_obstacles: 4
    nb_targets: 2

    max_attempts: 100
    max_steps: 200

  - name: eval5_random_5
    width: 128
    height: 64

    agent_mode: random
    env_mode: random

    nb_agents: 3
    nb_static_obstacles: 6
    nb_moving_obstacles: 5
    nb_targets: 2

    max_attempts: 100
    max_steps: 200

  - name: eval6_warehouse_1
    width: 128
    height: 64

    agent_mode: random
    env_mode: warehouse

    nb_agents: 1
    nb_moving_obstacles: 3
    nb_targets: 2

    margin: 2
    max_attempts: 100
    max_steps: 200

  - name: eval7_warehouse_2
    width: 128
    height: 64

    agent_mode: random
    env_mode: warehouse

    nb_agents: 2
    nb_moving_obstacles: 3
    nb_targets: 2

    margin: 2
    max_attempts: 100
    max_steps: 200

  - name: eval8_warehouse_3
    width: 128
    height: 64

    agent_mode: random
    env_mode: warehouse

    nb_agents: 5
    nb_moving_obstacles: 0
    nb_targets: 2

    margin: 2
    max_attempts: 100
    max_steps: 200

  - name: eval9_crossing_1
    width: 64
    height: 64

    agent_mode: crossing
    env_mode: crossing

    nb_agents: 1
    nb_static_obstacles: 0
    nb_moving_obstacles: 4

    max_attempts: 100
    max_steps: 200

  - name: eval10_crossing_2
    width: 64
    height: 64

    agent_mode: crossing
    env_mode: crossing

    nb_agents: 3
    nb_static_obstacles: 0
    nb_moving_obstacles: 2

    max_attempts: 100
    max_steps: 200
