train_tasks:
  - name: task1
    env_config: task1
    agent_config: agent_1
    reward_config: reward_1
    n_steps: 100_000

  - name: task2
    env_config: task2
    agent_config: agent_1
    reward_config: reward_1
    n_steps: 300_000

  - name: task3
    env_config: task3
    agent_config: agent_1
    reward_config: reward_1
    n_steps: 300_000

  - name: task4
    env_config: task4
    agent_config: agent_1
    reward_config: reward_1
    n_steps: 300_000

  - name: task5
    env_config: task5
    agent_config: agent_1
    reward_config: reward_1
    n_steps: 300_000

  - name: task6
    env_config: task6
    agent_config: agent_1
    reward_config: reward_1
    n_steps: 300_000

  - name: task7
    env_config: task7
    agent_config: agent_1
    reward_config: reward_1
    n_steps: 300_000

  - name: task8
    env_config: task8
    agent_config: agent_1
    reward_config: reward_1
    n_steps: 300_000

  - name: task9
    env_config: task9
    agent_config: agent_1
    reward_config: reward_1
    n_steps: 300_000

  - name: task10
    env_config: task10
    agent_config: agent_1
    reward_config: reward_1
    n_steps: 300_000

eval_tasks:
  - name: eval1_random_1
    env_config: eval1_random_1
    agent_config: agent_1
    reward_config: reward_1
    n_steps: null

  - name: eval2_random_2
    env_config: eval2_random_2
    agent_config: agent_1
    reward_config: reward_1
    n_steps: null

  - name: eval3_random_3
    env_config: eval3_random_3
    agent_config: agent_1
    reward_config: reward_1
    n_steps: null

  - name: eval4_random_4
    env_config: eval4_random_4
    agent_config: agent_1
    reward_config: reward_1
    n_steps: null

  - name: eval5_random_5
    env_config: eval5_random_5
    agent_config: agent_1
    reward_config: reward_1
    n_steps: null

  - name: eval6_warehouse_1
    env_config: eval6_warehouse_1
    agent_config: agent_1
    reward_config: reward_1
    n_steps: null

  - name: eval7_warehouse_2
    env_config: eval7_warehouse_2
    agent_config: agent_1
    reward_config: reward_1
    n_steps: null

  - name: eval8_warehouse_3
    env_config: eval8_warehouse_3
    agent_config: agent_1
    reward_config: reward_1
    n_steps: null

  - name: eval9_crossing_1
    env_config: eval9_crossing_1
    agent_config: agent_1
    reward_config: reward_1
    n_steps: null

  - name: eval10_crossing_2
    env_config: eval10_crossing_2
    agent_config: agent_1
    reward_config: reward_1
    n_steps: null
